name: ARIX Validate
on:
  push:
    paths:
      - 'arix-16/schema/**'
      - 'arix-16/examples/**'
      - 'arix-16/config/**'
      - 'scripts/ajv_check.mjs'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm i -g ajv ajv-cli ajv-formats

      - name: Debug sample presence
        run: |
          ls -la arix-16/examples/exports_sample || true

      - name: Validate with config (JSON/JSONL両対応)
        run: |
          node scripts/ajv_check.mjs \
            --schema ./arix-16/schema/arix16.schema.json \
            --data   ./arix-16/examples/exports_sample \
            --config ./arix-16/config/ajv_config.json