name: ARIX Validate

on:
  push:
    paths:
      - 'arix-16/schema/**'
      - 'arix-16/examples/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install AJV CLI
        run: npm install -g ajv-cli ajv-formats

      - name: Debug sample presence
        run: |
          ls -la arix-16/examples/exports_sample || true
          test -f arix-16/examples/exports_sample/taps_arix16_2025-W33.json && echo "FOUND JSON" || (echo "MISSING JSON"; exit 2)

      - name: Validate NDJSON (each line)
        run: |
          set -e
          SCHEMA='./arix-16/schema/arix16.schema.json'
          JSONL_GLOB='arix-16/examples/exports_sample/*.jsonl'

          if compgen -G "$JSONL_GLOB" > /dev/null; then
            for f in $JSONL_GLOB; do
              echo "::group::Validating NDJSON file: $f"
              while IFS= read -r line; do
                printf "%s" "$line" | ajv validate -c ajv-formats -s "$SCHEMA" -d - --spec draft2020
              done < <(awk 'NF && $0 !~ /^#/' "$f")
              echo "::endgroup::"
            done
          else
            echo "⚠️ No .jsonl files found under arix-16/examples/exports_sample/ (skipping)."
          fi